version: 2.1
jobs:
  build:
    working_directory: ~/SpringPetClinic/SpringPetClinic
orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
